export const categoryContent = [
    { value: "writing", label: "Writing" },
    { value: "seo", label: "SEO" },
    { value: "crypto", label: "Crypto" },
    { value: "crm", label: "Customer Relationship Management (CRM)" },
    { value: "project_management", label: "Project Management" },
    { value: "email_marketing", label: "Email Marketing" },
    { value: "social_media_management", label: "Social Media Management" },
    { value: "ecommerce", label: "E-commerce" },
    { value: "accounting", label: "Accounting" },
    { value: "hr", label: "Human Resources" },
    { value: "file_sharing", label: "File Sharing & Collaboration" },
    { value: "analytics", label: "Analytics & Data Visualization" },
    { value: "erp", label: "Enterprise Resource Planning (ERP)" },
    { value: "customer_support", label: "Customer Support" },
    { value: "marketing_automation", label: "Marketing Automation" },
    { value: "devops", label: "DevOps & Monitoring" },
    { value: "cloud_storage", label: "Cloud Storage" },
    { value: "video_conferencing", label: "Video Conferencing" },
    { value: "security", label: "Security & Compliance" },
    { value: "billing", label: "Billing & Invoicing" },
    { value: "elearning", label: "E-learning & Education" },
    { value: "task_management", label: "Task Management" },
    { value: "inventory_management", label: "Inventory Management" },
    { value: "design_tools", label: "Design Tools" },
    { value: "api_management", label: "API Management" },
    { value: "it_service_management", label: "IT Service Management" },
    { value: "collaboration", label: "Collaboration Tools" }
];
